spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foo?useSSL=false&useUnicode=true&characterEncoding=UTF-8&verifyServerCertificate=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: f
    password:
    hikari:
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
      connection-timeout: 20000
      connection-test-query: select 1
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
    initialization-mode: never
  #    schema: classpath:data/*schema.sql
  #  jpa:
  #    properties:
  #      hibernate:
  #        format_sql: true
  #        show_sql: false
  #        dialect: org.hibernate.dialect.MySQL8Dialect
  #        enable_lazy_load_no_trans: true
  #        event:
  #          merge:
  #            entity_copy_observer: allow
  #        jdbc:
  #          batch_size: 10
  #    open-in-view: false
  jackson:
    default-property-inclusion: non_empty
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    mapper:
      DEFAULT_VIEW_INCLUSION: false
  main:
    banner-mode: "off"
  output:
    ansi:
      enabled: always
  mvc:
    view:
      suffix: .html
logging:
  level:
    spring.springframework.web: debug
    com.f.mapper: debug
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapperxml/*.xml
